import os
from abc import ABCMeta, abstractmethod
from pprint import pprint

from ..parallel import mpiroot


class WavefunctionLoader(object):
    """A wavefunction loader that can load the wavefunction generated by given
    DFT codes into memory, stored as a Wavefunction object.
    """

    __metaclass__ = ABCMeta

    def __init__(self, memory="critical"):
        self.wfc = None
        self.memory = memory
        self.scan()
        self.info()

    @abstractmethod
    def scan(self):
        """Scan current directory, construct wavefunction object"""
        if mpiroot:
            print(
                f'\n{self.__class__.__name__}: scanning current working directory "{os.getcwd()}"...\n'
            )

    @abstractmethod
    def load(self, iorbs, sdm):
        """Load read space KS orbitals to memory, store in wfc.iorb_psir_map.

        Args:
            iorbs: a list of integers representing orbital indices.
            sdm: a SymmetricDistributedMatrix object indicating how the wavefunction is distributed.

        Returns:
            After load is called, the wavefunction will be loaded into self.wfc.
        """
        if mpiroot:
            print(
                f'\n{self.__class__.__name__}: loading orbitals into memory... (memory mode: "{self.memory}")\n'
            )

    def info(self):
        if mpiroot:
            wfc = self.wfc
            print(
                f"   nuwfcs = {wfc.nuorbs}, ndwfcs = {wfc.ndorbs}, nwfcs = {wfc.norbs}"
            )
            for iorb in range(wfc.norbs):
                print(
                    f"     spin = {wfc.iorb_sb_map[iorb][0]}     band = {wfc.iorb_sb_map[iorb][1]}     file = {wfc.iorb_fname_map[iorb]}"
                )
            print("\nSystem Overview:")
            print("  Cell: ")
            pprint(wfc.cell.__dict__, indent=4)
            print("  FFT Grid: ")
            pprint(wfc.ft.__dict__, indent=4)
