name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    container: miccomcenter/bot:gcc1340_0001

    steps:
    - uses: actions/checkout@v7
    - name: Lint
      run: |
        pip3 install -q -U pip
        pip3 install -q -U black
        black pyzfs
    - name: Build
      run: |
        pip3 install -q -U numpy
        pip3 install -q -U setuptools
        pip3 install .
    - name: Test
      run: |
        pip3 install -q -U pytest
        pip3 install -q -U gpaw
        cd examples
        sh run_test.sh
        pytest
    - name: Archive artifacts
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: artifacts
        path: |
          examples/o2_qbox_xml
          examples/o2_qe_hdf5
          examples/c3h6_gpaw
          examples/c3h6_gpaw_ae
        retention-days: 1
