name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    container: miccomcenter/bot:gcc1340_0001

    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: |
        pip3 install -q -U pip
        pip3 install -q -U numpy
        pip3 install -q -U pytest
        pip3 install -q -U setuptools
        pip3 install .
    - name: Test
      run: |
        cd examples
        cd o2_qbox_xml
        pyzfs --wfcfmt qbox --filename o2.xml > zfs.out
        cd ..
        cd o2_qe_hdf5
        pyzfs --wfcfmt qeh5 --memory high > zfs.out
        cd ..
        pytest
