name: Pages

on:
  push:
    branches:
      - master

permissions:
    contents: write

jobs:
  doc:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:latest

    steps:
    - uses: actions/checkout@v5
    - name: Init
      run: |
        apt-get update
        apt-get install -qq make
        apt-get install -qq pandoc
        pip install -q -U pip
        pip install -q -U nbsphinx
        pip install -q -U sphinx_rtd_theme
    - name: Build
      run: |
        pip install .
        sphinx-build doc _build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
