name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: |
        conda install black
        black --check --diff --color pyzfs
